In [10]:
!pip install vecstack

In [35]:
from vecstack import stacking
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
#from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE
from sklearn.svm import SVC
from collections import Counter #for Smote,
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [36]:
import pandas as pd

In [37]:
train_data = pd.read_csv(r"C:\Users\hgaje\Desktop\ML5\Cell Phone Churn - TRAIN-1.csv")
print(train_data.shape)

(1695, 24)


In [38]:
test_data = pd.read_csv(r"C:\Users\hgaje\Desktop\ML5\Cell Phone Churn - TEST-1.csv")
print(test_data.shape)

(375, 24)


In [39]:
train_data.columns

Index(['MOUMO', 'MOUPMO', 'MOU3MO', 'MOUCH1M', 'MOUCH3M', 'CUM3MCH', 'CUSTMOS',
       'LONGD', 'CALLW', 'LINES', 'VOICEM', 'CELL', 'CONVB', 'SEX', 'INCOME',
       'SPORTS', 'NATURE', 'ARTS', 'HRS_TV', 'TRAVEL', 'EDUC', 'TOTMOU',
       'TOTCHNG', 'TARGET'],
      dtype='object')

In [40]:
test_data.columns

Index(['MOUMO', 'MOUPMO', 'MOU3MO', 'MOUCH1M', 'MOUCH3M', 'CUM3MCH', 'CUSTMOS',
       'LONGD', 'CALLW', 'LINES', 'VOICEM', 'CELL', 'CONVB', 'SEX', 'INCOME',
       'SPORTS', 'NATURE', 'ARTS', 'HRS_TV', 'TRAVEL', 'EDUC', 'TOTMOU',
       'TOTCHNG', 'TARGET'],
      dtype='object')

In [41]:
categorical_columns = train_data.select_dtypes(include=['object', 'category'])

# Print the list of categorical columns
print("Categorical columns:", categorical_columns.columns)

Categorical columns: Index(['CONVB', 'SEX', 'SPORTS', 'ARTS', 'TRAVEL', 'EDUC'], dtype='object')


In [42]:
Target_Train_Cols = train_data['TARGET']#make copy of target column
train_data = train_data.drop(['TARGET'], axis=1) #extracting training data without the target column

print(train_data.shape)

(1695, 23)


In [43]:
Target_Test_Cols = test_data['TARGET']#make copy of target column
test_data = test_data.drop(['TARGET'], axis=1) #extracting training data without the target column

print(test_data.shape)

(375, 23)


In [44]:
#DROP COLUMNS WITH LOTS OF MISSING VALUES===============================
#CAN ALSO DROP ROWS WITH LOTS OF MISSING VALUES
#Combine Train data and test data first so that the SAME COLUMNS are DROPPED in each
combined_Data = pd.concat([train_data, test_data], keys=[0,1])
combined_Data.isnull().sum().sort_values(ascending=False)

MOUMO      0
CONVB      0
TOTMOU     0
EDUC       0
TRAVEL     0
HRS_TV     0
ARTS       0
NATURE     0
SPORTS     0
INCOME     0
SEX        0
CELL       0
MOUPMO     0
VOICEM     0
LINES      0
CALLW      0
LONGD      0
CUSTMOS    0
CUM3MCH    0
MOUCH3M    0
MOUCH1M    0
MOU3MO     0
TOTCHNG    0
dtype: int64

In [45]:
td1 = combined_Data.copy()

In [106]:
# OneHotEncoding

In [46]:
#DO ONE-HOT ENCODING ON CATEGORICAL VARIABLES==============================================
#The below function returns a list of categorical features which are not numeric. 
train_cat_cols = td1.select_dtypes(exclude=['float','int']).columns #selecting the categorical columns
print(train_cat_cols.shape)
print(train_cat_cols)

#If there are categorical columns which are encoded as numeric ones 
#then we need to explicitly enter the column names in a list and concatenate the two lists in python.
#ONE-HOT ENCODING-generate one-hot encoding on a common basis -THIS TAKES 30 MINS

combined_Data = pd.get_dummies(td1,train_cat_cols)
combined_Data.head(10)

(6,)
Index(['CONVB', 'SEX', 'SPORTS', 'ARTS', 'TRAVEL', 'EDUC'], dtype='object')


MOUMO  MOUPMO  MOU3MO  MOUCH1M  MOUCH3M  CUM3MCH  CUSTMOS  LONGD  CALLW  \
0 0    105      15      99       90      -84        6       11      0      0   
  1    999    1200    1145     -201       55     -146        3      1      1   
  2      5       2       1        3        1        4       23      0      0   
  3    600     456     398      144       58      202       13      0      1   
  4      2       0       0        0        0        0        1      0      0   
  5    678    1222     598     -544      624       80       30      1      1   
  6    110      98      56       12       42       54       15      1      0   
  7     97      56      97       41      -41        0        8      0      0   
  8     45      23      66       22      -43      -21       44      0      0   
  9     53      34      29       19        5       24       50      1      1   

     LINES  ...  TRAVEL_Domestic  TRAVEL_InterGalactic  TRAVEL_International  \
0 0      2  ...                0                     0                     0   
  1      2  ...                1                     0                     0   
  2      1  ...                0                     0                     1   
  3      1  ...                0                     0                     1   
  4      1  ...                1                     0                     0   
  5      2  ...                0                     0                     1   
  6      1  ...                0                     1                     0   
  7      1  ...                1                     0                     0   
  8      1  ...                0                     0                     1   
  9      1  ...                0                     0                     0   

     TRAVEL_None  EDUC_Bachelors  EDUC_Elementary  EDUC_GED  EDUC_HighSchool  \
0 0            1               1                0         0                0   
  1            0               0                0         0                0   
  2            0               0                0         0                1   
  3            0               0                0         0                0   
  4            0               0                0         0                1   
  5            0               0                0         0                1   
  6            0               0                0         0                1   
  7            0               0                0         0                1   
  8            0               0                0         0                0   
  9            1               0                0         1                0   

     EDUC_Masters  EDUC_PhD  
0 0             0         0  
  1             1         0  
  2             0         0  
  3             1         0  
  4             0         0  
  5             0         0  
  6             0         0  
  7             0         0  
  8             0         1  
  9             0         0  

[10 rows x 40 columns]

In [47]:
#Separate Train data and test data
train_data = combined_Data.xs(0)
test_data = combined_Data.xs(1)
print(train_data.shape)
print(test_data.shape)

train_data=pd.concat([train_data,Target_Train_Cols], axis=1)
test_data=pd.concat([test_data,Target_Test_Cols], axis=1)
print(train_data.shape)
print(test_data.shape)

(1695, 40)
(375, 40)
(1695, 41)
(375, 41)


In [48]:
categorical_columns = train_data.select_dtypes(include=['object', 'category'])

# Print the list of categorical columns
print("Categorical columns:", categorical_columns.columns)

Categorical columns: Index([], dtype='object')


No categorical columns: all are encoded

In [44]:
target_counts = train_data['TARGET'].value_counts()

In [49]:
target_counts_test = test_data['TARGET'].value_counts()
print(target_counts_test)

0    235
1    140
Name: TARGET, dtype: int64


In [107]:
#SMOTE

In [51]:
y_train = train_data['TARGET']
X_train = train_data.drop('TARGET',axis=1)
y_test = test_data['TARGET']
X_test = test_data.drop('TARGET',axis=1)

In [52]:
print('Original dataset shape %s' % Counter(y_train))
sm = SMOTE(sampling_strategy=0.8)
X_res, y_res = sm.fit_resample(X_train, y_train)
print('Resampled dataset shape %s' % Counter(y_res))

Original dataset shape Counter({0: 1052, 1: 643})
Resampled dataset shape Counter({0: 1052, 1: 841})


We can say that data is not to much imbalance but we are using to SMOTE to get perfectly balanced data

In [53]:
# MLP 

In [54]:
from sklearn.neural_network import MLPClassifier

In [55]:
mlp = MLPClassifier(max_iter=100)
mlp.fit(X_res, y_res)

MLPClassifier(max_iter=100)

In [56]:
mlp_predict=mlp.predict(X_test)
print("accuracy Score (training) for MultiLayer Perceptron:{0:6f}".format(mlp.score(X_test,y_test)))
print("Confusion Matrix for MultiLayer Perceptron:")
print(confusion_matrix(y_test,mlp_predict))

accuracy Score (training) for MultiLayer Perceptron:0.733333
Confusion Matrix for MultiLayer Perceptron:
[[234   1]
 [ 99  41]]


In [57]:
print("\nClassification Report:")
print(classification_report(y_test, mlp_predict))


Classification Report:
              precision    recall  f1-score   support

           0       0.70      1.00      0.82       235
           1       0.98      0.29      0.45       140

    accuracy                           0.73       375
   macro avg       0.84      0.64      0.64       375
weighted avg       0.80      0.73      0.68       375



In [58]:
# SVC Linear

In [59]:
from sklearn.svm import LinearSVC 

In [60]:
linsvm = LinearSVC(max_iter=300) 
linsvm.fit(X_train, y_train)

LinearSVC(max_iter=300)

In [61]:
linsvm_predict=linsvm.predict(X_test) 
print("accuracy Score (training) for Linear SVM Classifier:{0:6f}".format(linsvm.score(X_test,y_test))) 
print("Confusion Matrix for Linear SVM Classifier:") 
print(confusion_matrix(y_test,linsvm_predict))

accuracy Score (training) for Linear SVM Classifier:0.648000
Confusion Matrix for Linear SVM Classifier:
[[232   3]
 [129  11]]


In [62]:
print("\nClassification Report:")
print(classification_report(y_test, linsvm_predict))


Classification Report:
              precision    recall  f1-score   support

           0       0.64      0.99      0.78       235
           1       0.79      0.08      0.14       140

    accuracy                           0.65       375
   macro avg       0.71      0.53      0.46       375
weighted avg       0.70      0.65      0.54       375



In [63]:
#  Decision Tree Classifier

In [64]:
from sklearn.tree import DecisionTreeClassifier

In [65]:
clf = DecisionTreeClassifier()

In [66]:
clf.fit(X_train,y_train)
clf_predict=clf.predict(X_test)

In [67]:
print("accuracy Score (training) for Decision Tree:{0:6f}".format(clf.score(X_test,y_test)))
print("Confusion Matrix for Decision Tree")
print(confusion_matrix(y_test,clf_predict))

accuracy Score (training) for Decision Tree:0.994667
Confusion Matrix for Decision Tree
[[235   0]
 [  2 138]]


In [68]:
print("\nClassification Report:")
print(classification_report(y_test, clf_predict))


Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       235
           1       1.00      0.99      0.99       140

    accuracy                           0.99       375
   macro avg       1.00      0.99      0.99       375
weighted avg       0.99      0.99      0.99       375



In [69]:
# Random Forest Classifier

In [70]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [71]:
rfc_predict=rfc.predict(X_test)

In [72]:
print("accuracy Score (training) for RandomForest:{0:6f}".format(rfc.score(X_test,y_test)))
print("Confusion Matrix for Random Forest:")
print(confusion_matrix(y_test,rfc_predict))

accuracy Score (training) for RandomForest:0.994667
Confusion Matrix for Random Forest:
[[235   0]
 [  2 138]]


In [73]:
print("\nClassification Report:")
print(classification_report(y_test, rfc_predict))


Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       235
           1       1.00      0.99      0.99       140

    accuracy                           0.99       375
   macro avg       1.00      0.99      0.99       375
weighted avg       0.99      0.99      0.99       375



In [75]:
#Hyperparameter Tuning on Random Forest

In [76]:
parameters={'n_estimators': range(1,30,3),'min_samples_split' : range(10,100,10),'max_depth': range(1,30,3)}

In [77]:
#Hyperparameter tuning for random forest classifier
rfc_random = RandomizedSearchCV(rfc,parameters,n_iter=15)
rfc_random.fit(X_train, y_train)
grid_parm_rfc=rfc_random.best_params_
print(grid_parm_rfc)

{'n_estimators': 22, 'min_samples_split': 30, 'max_depth': 16}


Best parameters:
n-estimators = 22
minimum samples split = 30
maximum depth = 16

In [108]:
#Construct Random Forest with best parameters

In [109]:
rfc= RandomForestClassifier(**grid_parm_rfc)
rfc.fit(X_train,y_train)
rfc_predict = rfc.predict(X_test)

In [110]:
print("accuracy Score (training) after hypertuning for Random Forest:{0:6f}".format(rfc.score(X_test,y_test)))
print("Confusion Matrix after hypertuning for Random Forest:")
print(confusion_matrix(y_test,rfc_predict))
print("=== Classification Report ===")
print(classification_report(y_test,rfc_predict))

accuracy Score (training) after hypertuning for Random Forest:0.994667
Confusion Matrix after hypertuning for Random Forest:
[[235   0]
 [  2 138]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       235
           1       1.00      0.99      0.99       140

    accuracy                           0.99       375
   macro avg       1.00      0.99      0.99       375
weighted avg       0.99      0.99      0.99       375



In [81]:
#get cross-validation report
rfc_cv_score = cross_val_score(rfc, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ",rfc_cv_score.mean())


=== All AUC Scores ===
[0.99771521 0.99882075 1.         0.99978022 0.9985348  0.9874256
 0.99903274 1.         0.99821429 0.9984375 ]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.9977961104343768


In [83]:
#Feature Selection

In [84]:
!pip install mlxtend

In [85]:
# Import libraries for feature selection
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_classif
#from mlxtend.feature_selection import SequentialFeatureSelector as SFS

In [88]:
# Feature selection using Random Forest using feature_importances_

In [89]:
#Do feature selection using a classification model - DECISION TREE
print(rfc.feature_importances_)

#print sorted list of important features
importances = rfc.feature_importances_
indices = np.argsort(importances)[-5:] #the list is in ascending order
print("\n top 5 features = ", indices, "\n")

[2.36434419e-02 8.48369370e-02 4.72107977e-02 4.84508680e-02
 2.33905349e-01 5.59892674e-02 3.02487995e-02 4.99299429e-03
 1.85639676e-02 1.18337043e-02 1.30755784e-02 1.08958197e-02
 7.25575427e-02 1.98270755e-03 1.19170882e-02 1.46885064e-02
 1.07119192e-01 2.61110669e-02 2.65249190e-02 4.65830358e-03
 1.83771736e-04 1.89543988e-02 4.71132655e-03 1.61208370e-02
 3.04236818e-03 3.82766051e-03 1.41522336e-04 1.50841737e-03
 6.26441639e-03 1.53220070e-02 1.26724075e-03 2.05777656e-02
 2.71516665e-02 2.71592249e-03 4.97790483e-04 7.27348333e-03
 1.15469375e-03 1.18836104e-02 1.74470248e-03 6.44954742e-03]

 top 5 features =  [ 5 12  1 16  4] 



In [93]:
# Let's get strted with stacking

In [94]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from vecstack import stacking

In [95]:
models = [MLPClassifier(), LinearSVC(), RandomForestClassifier(), DecisionTreeClassifier()]                  

In [96]:
S_Train, S_Test = stacking(models,                   
                           X_res, y_res, X_test,   
                           regression=False, 
     
                           mode='oof_pred_bag', 
       
                           needs_proba=False,
         
                           save_dir=None, 
            
                           metric=accuracy_score, 
    
                           n_folds=4, 
                 
                           stratified=True,
            
                           shuffle=True,  
            
                           random_state=0,    
         
                           verbose=2)

task:         [classification]
n_classes:    [2]
metric:       [accuracy_score]
mode:         [oof_pred_bag]
n_models:     [4]

model  0:     [MLPClassifier]
    fold  0:  [0.63080169]
    fold  1:  [0.65327696]
    fold  2:  [0.68076110]
    fold  3:  [0.65327696]
    ----
    MEAN:     [0.65452917] + [0.01770765]
    FULL:     [0.65451664]

model  1:     [LinearSVC]
    fold  0:  [0.49367089]
    fold  1:  [0.60887949]
    fold  2:  [0.59196617]
    fold  3:  [0.58139535]
    ----
    MEAN:     [0.56897798] + [0.04456999]
    FULL:     [0.56893819]

model  2:     [RandomForestClassifier]
    fold  0:  [0.98523207]
    fold  1:  [0.99154334]
    fold  2:  [0.98731501]
    fold  3:  [0.98520085]
    ----
    MEAN:     [0.98732282] + [0.00258297]
    FULL:     [0.98732171]

model  3:     [DecisionTreeClassifier]
    fold  0:  [0.98312236]
    fold  1:  [0.98942918]
    fold  2:  [0.98731501]
    fold  3:  [0.98520085]
    ----
    MEAN:     [0.98626685] + [0.00235176]
    FULL:     [0.9

In [101]:
#  KNN for Stacking Clssification

In [102]:
model = KNeighborsClassifier(n_neighbors=5)

In [103]:
model = model.fit(S_Train, y_res)
y_pred_test = model.predict(S_Test)

In [104]:
print("accuracy Score for stacked model:{0:6f}".format(model.score(S_Test,y_test)))
print("Confusion Matrix for Random Forest:")
print(confusion_matrix(y_test,y_pred_test))

accuracy Score for stacked model:0.994667
Confusion Matrix for Random Forest:
[[235   0]
 [  2 138]]


In [105]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred_test))


Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       235
           1       1.00      0.99      0.99       140

    accuracy                           0.99       375
   macro avg       1.00      0.99      0.99       375
weighted avg       0.99      0.99      0.99       375

